[tool.poetry]
name = "toy-hierarchy"
version = "0.1.0"
description = "\"Toy Models of Hierarchy\""
authors = ["Daniel Lee <dajale423@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
